# Generated by Django 3.0.3 on 2021-05-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='Final_Amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='Raw_amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
