# Generated by Django 3.0.3 on 2021-05-03 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemssold',
            name='quantity_free',
        ),
    ]
