# Generated by Django 3.0.3 on 2021-05-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0004_auto_20210503_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('address', models.CharField(max_length=264)),
                ('gst', models.CharField(max_length=264)),
            ],
        ),
    ]
