# Generated by Django 3.0.3 on 2021-05-03 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0005_suppliers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suppliers',
        ),
    ]
